[theme]
primaryColor = "#e10600"            # F1 Red
backgroundColor = "#0f0f0f"         # Deep charcoal
secondaryBackgroundColor = "#202020"  # Gray-black
textColor = "#f0f0f0"               # Light text
font = "sans serif"
base = "dark"
